apiVersion: apps/v1
kind: Deployment
metadata:
  name: ggit-app
  labels:
    app: ggit-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ggit-app
  template:
    metadata:
      labels:
        app: ggit-app
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: build-output
              mountPath: /usr/share/nginx/html
        - name: builder
          image: johnbeck/autograv:v1
          imagePullPolicy: Always
          env:
            - name: GITHUB_REPO
              value: "https://github.com/definitiontv/grav-skeleton-gateway-site.git"
            - name: POLL_INTERVAL
              value: "30"
          volumeMounts:
            - name: build-output
              mountPath: /build
      volumes:
        - name: build-output
          emptyDir: {}
---
kind: Service
apiVersion: v1
metadata:
  name: ggit-app
  labels:
    app: ggit-app
spec:
  selector:
    app: ggit-app
  ports:
    - port: 80
      name: http
      targetPort: 80
  type: LoadBalancer
